"""Client, models, and URL construction for Repertoire."""

from ._builder import RepertoireBuilder, RepertoireBuilderWithSecrets
from ._client import DiscoveryClient
from ._config import (
    ApiVersionRule,
    BaseRegistryEntry,
    BaseServiceRule,
    DataServiceRule,
    DatasetConfig,
    DatasetRegistryEntry,
    EnvironmentConfig,
    GmsRegistryEntry,
    HipsConfig,
    HipsDatasetConfig,
    HipsLegacyConfig,
    InfluxDatabaseConfig,
    InternalServiceRule,
    IvoaContentLevel,
    IvoaContentType,
    IvoaStandardId,
    MultiRecordRegistryEntry,
    QuotaLabelConfig,
    RegistryEntry,
    RepertoireSettings,
    ServiceRules,
    SiaDatasetRegistryEntry,
    SiaRegistryEntry,
    SodaRegistryEntry,
    TapDatasetEntry,
    TapOutputFormatConfig,
    TapRegistryEntry,
    UiServiceRule,
    VersionedServiceRule,
)
from ._dependencies import DiscoveryDependency, discovery_dependency
from ._exceptions import (
    RepertoireError,
    RepertoireUrlError,
    RepertoireValidationError,
    RepertoireWebError,
)
from ._mock import register_mock_discovery
from ._models import (
    ApiService,
    ApiVersion,
    BaseService,
    DataService,
    Dataset,
    Discovery,
    Environment,
    InfluxDatabase,
    InfluxDatabaseWithCredentials,
    InternalService,
    QuotaLabel,
    Services,
    UiService,
)

__all__ = [
    "ApiService",
    "ApiVersion",
    "ApiVersionRule",
    "BaseRegistryEntry",
    "BaseService",
    "BaseServiceRule",
    "DataService",
    "DataServiceRule",
    "Dataset",
    "DatasetConfig",
    "DatasetRegistryEntry",
    "Discovery",
    "DiscoveryClient",
    "DiscoveryDependency",
    "Environment",
    "EnvironmentConfig",
    "GmsRegistryEntry",
    "HipsConfig",
    "HipsDatasetConfig",
    "HipsLegacyConfig",
    "InfluxDatabase",
    "InfluxDatabaseConfig",
    "InfluxDatabaseWithCredentials",
    "InternalService",
    "InternalServiceRule",
    "IvoaContentLevel",
    "IvoaContentType",
    "IvoaStandardId",
    "MultiRecordRegistryEntry",
    "QuotaLabel",
    "QuotaLabelConfig",
    "RegistryEntry",
    "RepertoireBuilder",
    "RepertoireBuilderWithSecrets",
    "RepertoireError",
    "RepertoireSettings",
    "RepertoireUrlError",
    "RepertoireValidationError",
    "RepertoireWebError",
    "ServiceRules",
    "Services",
    "SiaDatasetRegistryEntry",
    "SiaRegistryEntry",
    "SodaRegistryEntry",
    "TapDatasetEntry",
    "TapOutputFormatConfig",
    "TapRegistryEntry",
    "UiService",
    "UiServiceRule",
    "VersionedServiceRule",
    "discovery_dependency",
    "register_mock_discovery",
]
